import {translations_common} from "./translations_common";

export type TArgVueTrKeys = keyof typeof translations_common
// 'search'
// | 'not_found'
// | 'search_results'
// | 'recent_searches'
// | 'no_recent_searches'
// | 'no_results'
// | 'warning'
// | 'yes'
// | 'no'
// | 'something_went_wrong'
// | 'news'
// | 'all'
// | 'upload'
// | 'cancel'
// | 'save'
// | 'saved_successfully'
// | 'type_at_least_X_characters'
