export type TArgVueTrKeys =
    'search'
    | 'not_found'
    | 'search_results'
    | 'recent_searches'
    | 'no_recent_searches'
    | 'warning'
    | 'yes'
    | 'no'
    | 'something_went_wrong'
    | 'news'
    | 'all'
    | 'upload'
    | 'cancel'
